// ThreeCanvas.js r32 - http://github.com/mrdoob/three.js
var THREE=THREE||{};THREE.Color=function(a){this.autoUpdate=true;this.setHex(a)};
THREE.Color.prototype={setRGB:function(a,b,c){this.r=a;this.g=b;this.b=c;if(this.autoUpdate){this.updateHex();this.updateStyleString()}},setHex:function(a){this.hex=~~a&16777215;if(this.autoUpdate){this.updateRGBA();this.updateStyleString()}},updateHex:function(){this.hex=~~(this.r*255)<<16^~~(this.g*255)<<8^~~(this.b*255)},updateRGBA:function(){this.r=(this.hex>>16&255)/255;this.g=(this.hex>>8&255)/255;this.b=(this.hex&255)/255},updateStyleString:function(){this.__styleString="rgb("+~~(this.r*255)+
","+~~(this.g*255)+","+~~(this.b*255)+")"},clone:function(){return new THREE.Color(this.hex)},toString:function(){return"THREE.Color ( r: "+this.r+", g: "+this.g+", b: "+this.b+", hex: "+this.hex+" )"}};THREE.Vector2=function(a,b){this.x=a||0;this.y=b||0};
THREE.Vector2.prototype={set:function(a,b){this.x=a;this.y=b;return this},copy:function(a){this.x=a.x;this.y=a.y;return this},addSelf:function(a){this.x+=a.x;this.y+=a.y;return this},add:function(a,b){this.x=a.x+b.x;this.y=a.y+b.y;return this},subSelf:function(a){this.x-=a.x;this.y-=a.y;return this},sub:function(a,b){this.x=a.x-b.x;this.y=a.y-b.y;return this},multiplyScalar:function(a){this.x*=a;this.y*=a;return this},unit:function(){this.multiplyScalar(1/this.length());return this},length:function(){return Math.sqrt(this.x*
this.x+this.y*this.y)},lengthSq:function(){return this.x*this.x+this.y*this.y},negate:function(){this.x=-this.x;this.y=-this.y;return this},clone:function(){return new THREE.Vector2(this.x,this.y)},toString:function(){return"THREE.Vector2 ("+this.x+", "+this.y+")"}};THREE.Vector3=function(a,b,c){this.x=a||0;this.y=b||0;this.z=c||0};
THREE.Vector3.prototype={set:function(a,b,c){this.x=a;this.y=b;this.z=c;return this},copy:function(a){this.x=a.x;this.y=a.y;this.z=a.z;return this},add:function(a,b){this.x=a.x+b.x;this.y=a.y+b.y;this.z=a.z+b.z;return this},addSelf:function(a){this.x+=a.x;this.y+=a.y;this.z+=a.z;return this},addScalar:function(a){this.x+=a;this.y+=a;this.z+=a;return this},sub:function(a,b){this.x=a.x-b.x;this.y=a.y-b.y;this.z=a.z-b.z;return this},subSelf:function(a){this.x-=a.x;this.y-=a.y;this.z-=a.z;return this},
cross:function(a,b){this.x=a.y*b.z-a.z*b.y;this.y=a.z*b.x-a.x*b.z;this.z=a.x*b.y-a.y*b.x;return this},crossSelf:function(a){var b=this.x,c=this.y,d=this.z;this.x=c*a.z-d*a.y;this.y=d*a.x-b*a.z;this.z=b*a.y-c*a.x;return this},multiply:function(a,b){this.x=a.x*b.x;this.y=a.y*b.y;this.z=a.z*b.z;return this},multiplySelf:function(a){this.x*=a.x;this.y*=a.y;this.z*=a.z;return this},multiplyScalar:function(a){this.x*=a;this.y*=a;this.z*=a;return this},divideSelf:function(a){this.x/=a.x;this.y/=a.y;this.z/=
a.z;return this},divideScalar:function(a){this.x/=a;this.y/=a;this.z/=a;return this},dot:function(a){return this.x*a.x+this.y*a.y+this.z*a.z},distanceTo:function(a){var b=this.x-a.x,c=this.y-a.y;a=this.z-a.z;return Math.sqrt(b*b+c*c+a*a)},distanceToSquared:function(a){var b=this.x-a.x,c=this.y-a.y;a=this.z-a.z;return b*b+c*c+a*a},length:function(){return Math.sqrt(this.x*this.x+this.y*this.y+this.z*this.z)},lengthSq:function(){return this.x*this.x+this.y*this.y+this.z*this.z},negate:function(){this.x=
-this.x;this.y=-this.y;this.z=-this.z;return this},normalize:function(){var a=Math.sqrt(this.x*this.x+this.y*this.y+this.z*this.z);a>0?this.multiplyScalar(1/a):this.set(0,0,0);return this},setLength:function(a){return this.normalize().multiplyScalar(a)},isZero:function(){return Math.abs(this.x)<1.0E-4&&Math.abs(this.y)<1.0E-4&&Math.abs(this.z)<1.0E-4},clone:function(){return new THREE.Vector3(this.x,this.y,this.z)},toString:function(){return"THREE.Vector3 ( "+this.x+", "+this.y+", "+this.z+" )"}};
THREE.Vector4=function(a,b,c,d){this.x=a||0;this.y=b||0;this.z=c||0;this.w=d||1};
THREE.Vector4.prototype={set:function(a,b,c,d){this.x=a;this.y=b;this.z=c;this.w=d;return this},copy:function(a){this.x=a.x;this.y=a.y;this.z=a.z;this.w=a.w||1;return this},add:function(a,b){this.x=a.x+b.x;this.y=a.y+b.y;this.z=a.z+b.z;this.w=a.w+b.w;return this},addSelf:function(a){this.x+=a.x;this.y+=a.y;this.z+=a.z;this.w+=a.w;return this},sub:function(a,b){this.x=a.x-b.x;this.y=a.y-b.y;this.z=a.z-b.z;this.w=a.w-b.w;return this},subSelf:function(a){this.x-=a.x;this.y-=a.y;this.z-=a.z;this.w-=a.w;
return this},multiplyScalar:function(a){this.x*=a;this.y*=a;this.z*=a;this.w*=a;return this},divideScalar:function(a){this.x/=a;this.y/=a;this.z/=a;this.w/=a;return this},lerpSelf:function(a,b){this.x+=(a.x-this.x)*b;this.y+=(a.y-this.y)*b;this.z+=(a.z-this.z)*b;this.w+=(a.w-this.w)*b},clone:function(){return new THREE.Vector4(this.x,this.y,this.z,this.w)},toString:function(){return"THREE.Vector4 ("+this.x+", "+this.y+", "+this.z+", "+this.w+")"}};
THREE.Ray=function(a,b){this.origin=a||new THREE.Vector3;this.direction=b||new THREE.Vector3};
THREE.Ray.prototype={intersectScene:function(a){var b,c,d=a.objects,e=[];a=0;for(b=d.length;a<b;a++){c=d[a];if(c instanceof THREE.Mesh)e=e.concat(this.intersectObject(c))}e.sort(function(f,i){return f.distance-i.distance});return e},intersectObject:function(a){function b(r,k,E,C){C=C.clone().subSelf(k);E=E.clone().subSelf(k);var K=r.clone().subSelf(k);r=C.dot(C);k=C.dot(E);C=C.dot(K);var I=E.dot(E);E=E.dot(K);K=1/(r*I-k*k);I=(I*C-k*E)*K;r=(r*E-k*C)*K;return I>0&&r>0&&I+r<1}var c,d,e,f,i,j,g,h,p,m,
n,q=a.geometry,u=q.vertices,v=[];c=0;for(d=q.faces.length;c<d;c++){e=q.faces[c];m=this.origin.clone();n=this.direction.clone();f=a.matrix.multiplyVector3(u[e.a].position.clone());i=a.matrix.multiplyVector3(u[e.b].position.clone());j=a.matrix.multiplyVector3(u[e.c].position.clone());g=e instanceof THREE.Face4?a.matrix.multiplyVector3(u[e.d].position.clone()):null;h=a.rotationMatrix.multiplyVector3(e.normal.clone());p=n.dot(h);if(p<0){h=h.dot((new THREE.Vector3).sub(f,m))/p;m=m.addSelf(n.multiplyScalar(h));
if(e instanceof THREE.Face3){if(b(m,f,i,j)){e={distance:this.origin.distanceTo(m),point:m,face:e,object:a};v.push(e)}}else if(e instanceof THREE.Face4)if(b(m,f,i,g)||b(m,i,j,g)){e={distance:this.origin.distanceTo(m),point:m,face:e,object:a};v.push(e)}}}return v}};
THREE.Rectangle=function(){function a(){f=d-b;i=e-c}var b,c,d,e,f,i,j=true;this.getX=function(){return b};this.getY=function(){return c};this.getWidth=function(){return f};this.getHeight=function(){return i};this.getLeft=function(){return b};this.getTop=function(){return c};this.getRight=function(){return d};this.getBottom=function(){return e};this.set=function(g,h,p,m){j=false;b=g;c=h;d=p;e=m;a()};this.addPoint=function(g,h){if(j){j=false;b=g;c=h;d=g;e=h}else{b=b<g?b:g;c=c<h?c:h;d=d>g?d:g;e=e>h?
e:h}a()};this.add3Points=function(g,h,p,m,n,q){if(j){j=false;b=g<p?g<n?g:n:p<n?p:n;c=h<m?h<q?h:q:m<q?m:q;d=g>p?g>n?g:n:p>n?p:n;e=h>m?h>q?h:q:m>q?m:q}else{b=g<p?g<n?g<b?g:b:n<b?n:b:p<n?p<b?p:b:n<b?n:b;c=h<m?h<q?h<c?h:c:q<c?q:c:m<q?m<c?m:c:q<c?q:c;d=g>p?g>n?g>d?g:d:n>d?n:d:p>n?p>d?p:d:n>d?n:d;e=h>m?h>q?h>e?h:e:q>e?q:e:m>q?m>e?m:e:q>e?q:e}a()};this.addRectangle=function(g){if(j){j=false;b=g.getLeft();c=g.getTop();d=g.getRight();e=g.getBottom()}else{b=b<g.getLeft()?b:g.getLeft();c=c<g.getTop()?c:g.getTop();
d=d>g.getRight()?d:g.getRight();e=e>g.getBottom()?e:g.getBottom()}a()};this.inflate=function(g){b-=g;c-=g;d+=g;e+=g;a()};this.minSelf=function(g){b=b>g.getLeft()?b:g.getLeft();c=c>g.getTop()?c:g.getTop();d=d<g.getRight()?d:g.getRight();e=e<g.getBottom()?e:g.getBottom();a()};this.instersects=function(g){return Math.min(d,g.getRight())-Math.max(b,g.getLeft())>=0&&Math.min(e,g.getBottom())-Math.max(c,g.getTop())>=0};this.empty=function(){j=true;e=d=c=b=0;a()};this.isEmpty=function(){return j};this.toString=
function(){return"THREE.Rectangle ( left: "+b+", right: "+d+", top: "+c+", bottom: "+e+", width: "+f+", height: "+i+" )"}};THREE.Matrix3=function(){this.m=[]};THREE.Matrix3.prototype={transpose:function(){var a,b=this.m;a=b[1];b[1]=b[3];b[3]=a;a=b[2];b[2]=b[6];b[6]=a;a=b[5];b[5]=b[7];b[7]=a;return this}};
THREE.Matrix4=function(a,b,c,d,e,f,i,j,g,h,p,m,n,q,u,v){this.n11=a||1;this.n12=b||0;this.n13=c||0;this.n14=d||0;this.n21=e||0;this.n22=f||1;this.n23=i||0;this.n24=j||0;this.n31=g||0;this.n32=h||0;this.n33=p||1;this.n34=m||0;this.n41=n||0;this.n42=q||0;this.n43=u||0;this.n44=v||1;this.flat=Array(16);this.m33=new THREE.Matrix3};
THREE.Matrix4.prototype={identity:function(){this.n11=1;this.n21=this.n14=this.n13=this.n12=0;this.n22=1;this.n32=this.n31=this.n24=this.n23=0;this.n33=1;this.n43=this.n42=this.n41=this.n34=0;this.n44=1;return this},set:function(a,b,c,d,e,f,i,j,g,h,p,m,n,q,u,v){this.n11=a;this.n12=b;this.n13=c;this.n14=d;this.n21=e;this.n22=f;this.n23=i;this.n24=j;this.n31=g;this.n32=h;this.n33=p;this.n34=m;this.n41=n;this.n42=q;this.n43=u;this.n44=v;return this},copy:function(a){this.n11=a.n11;this.n12=a.n12;this.n13=
a.n13;this.n14=a.n14;this.n21=a.n21;this.n22=a.n22;this.n23=a.n23;this.n24=a.n24;this.n31=a.n31;this.n32=a.n32;this.n33=a.n33;this.n34=a.n34;this.n41=a.n41;this.n42=a.n42;this.n43=a.n43;this.n44=a.n44;return this},lookAt:function(a,b,c){var d=THREE.Matrix4.__tmpVec1,e=THREE.Matrix4.__tmpVec2,f=THREE.Matrix4.__tmpVec3;f.sub(a,b).normalize();d.cross(c,f).normalize();e.cross(f,d).normalize();this.n11=d.x;this.n12=d.y;this.n13=d.z;this.n14=-d.dot(a);this.n21=e.x;this.n22=e.y;this.n23=e.z;this.n24=-e.dot(a);
this.n31=f.x;this.n32=f.y;this.n33=f.z;this.n34=-f.dot(a);this.n43=this.n42=this.n41=0;this.n44=1;return this},multiplyVector3:function(a){var b=a.x,c=a.y,d=a.z,e=1/(this.n41*b+this.n42*c+this.n43*d+this.n44);a.x=(this.n11*b+this.n12*c+this.n13*d+this.n14)*e;a.y=(this.n21*b+this.n22*c+this.n23*d+this.n24)*e;a.z=(this.n31*b+this.n32*c+this.n33*d+this.n34)*e;return a},multiplyVector4:function(a){var b=a.x,c=a.y,d=a.z,e=a.w;a.x=this.n11*b+this.n12*c+this.n13*d+this.n14*e;a.y=this.n21*b+this.n22*c+this.n23*
d+this.n24*e;a.z=this.n31*b+this.n32*c+this.n33*d+this.n34*e;a.w=this.n41*b+this.n42*c+this.n43*d+this.n44*e;return a},crossVector:function(a){var b=new THREE.Vector4;b.x=this.n11*a.x+this.n12*a.y+this.n13*a.z+this.n14*a.w;b.y=this.n21*a.x+this.n22*a.y+this.n23*a.z+this.n24*a.w;b.z=this.n31*a.x+this.n32*a.y+this.n33*a.z+this.n34*a.w;b.w=a.w?this.n41*a.x+this.n42*a.y+this.n43*a.z+this.n44*a.w:1;return b},multiply:function(a,b){var c=a.n11,d=a.n12,e=a.n13,f=a.n14,i=a.n21,j=a.n22,g=a.n23,h=a.n24,p=a.n31,
m=a.n32,n=a.n33,q=a.n34,u=a.n41,v=a.n42,r=a.n43,k=a.n44,E=b.n11,C=b.n12,K=b.n13,I=b.n14,P=b.n21,D=b.n22,z=b.n23,L=b.n24,A=b.n31,J=b.n32,x=b.n33,B=b.n34,t=b.n41,Q=b.n42,w=b.n43,N=b.n44;this.n11=c*E+d*P+e*A+f*t;this.n12=c*C+d*D+e*J+f*Q;this.n13=c*K+d*z+e*x+f*w;this.n14=c*I+d*L+e*B+f*N;this.n21=i*E+j*P+g*A+h*t;this.n22=i*C+j*D+g*J+h*Q;this.n23=i*K+j*z+g*x+h*w;this.n24=i*I+j*L+g*B+h*N;this.n31=p*E+m*P+n*A+q*t;this.n32=p*C+m*D+n*J+q*Q;this.n33=p*K+m*z+n*x+q*w;this.n34=p*I+m*L+n*B+q*N;this.n41=u*E+v*P+
r*A+k*t;this.n42=u*C+v*D+r*J+k*Q;this.n43=u*K+v*z+r*x+k*w;this.n44=u*I+v*L+r*B+k*N;return this},multiplySelf:function(a){var b=this.n11,c=this.n12,d=this.n13,e=this.n14,f=this.n21,i=this.n22,j=this.n23,g=this.n24,h=this.n31,p=this.n32,m=this.n33,n=this.n34,q=this.n41,u=this.n42,v=this.n43,r=this.n44,k=a.n11,E=a.n21,C=a.n31,K=a.n41,I=a.n12,P=a.n22,D=a.n32,z=a.n42,L=a.n13,A=a.n23,J=a.n33,x=a.n43,B=a.n14,t=a.n24,Q=a.n34;a=a.n44;this.n11=b*k+c*E+d*C+e*K;this.n12=b*I+c*P+d*D+e*z;this.n13=b*L+c*A+d*J+e*
x;this.n14=b*B+c*t+d*Q+e*a;this.n21=f*k+i*E+j*C+g*K;this.n22=f*I+i*P+j*D+g*z;this.n23=f*L+i*A+j*J+g*x;this.n24=f*B+i*t+j*Q+g*a;this.n31=h*k+p*E+m*C+n*K;this.n32=h*I+p*P+m*D+n*z;this.n33=h*L+p*A+m*J+n*x;this.n34=h*B+p*t+m*Q+n*a;this.n41=q*k+u*E+v*C+r*K;this.n42=q*I+u*P+v*D+r*z;this.n43=q*L+u*A+v*J+r*x;this.n44=q*B+u*t+v*Q+r*a;return this},multiplyScalar:function(a){this.n11*=a;this.n12*=a;this.n13*=a;this.n14*=a;this.n21*=a;this.n22*=a;this.n23*=a;this.n24*=a;this.n31*=a;this.n32*=a;this.n33*=a;this.n34*=
a;this.n41*=a;this.n42*=a;this.n43*=a;this.n44*=a;return this},determinant:function(){var a=this.n11,b=this.n12,c=this.n13,d=this.n14,e=this.n21,f=this.n22,i=this.n23,j=this.n24,g=this.n31,h=this.n32,p=this.n33,m=this.n34,n=this.n41,q=this.n42,u=this.n43,v=this.n44;return d*i*h*n-c*j*h*n-d*f*p*n+b*j*p*n+c*f*m*n-b*i*m*n-d*i*g*q+c*j*g*q+d*e*p*q-a*j*p*q-c*e*m*q+a*i*m*q+d*f*g*u-b*j*g*u-d*e*h*u+a*j*h*u+b*e*m*u-a*f*m*u-c*f*g*v+b*i*g*v+c*e*h*v-a*i*h*v-b*e*p*v+a*f*p*v},transpose:function(){function a(b,c,
d){var e=b[c];b[c]=b[d];b[d]=e}a(this,"n21","n12");a(this,"n31","n13");a(this,"n32","n23");a(this,"n41","n14");a(this,"n42","n24");a(this,"n43","n34");return this},clone:function(){var a=new THREE.Matrix4;a.n11=this.n11;a.n12=this.n12;a.n13=this.n13;a.n14=this.n14;a.n21=this.n21;a.n22=this.n22;a.n23=this.n23;a.n24=this.n24;a.n31=this.n31;a.n32=this.n32;a.n33=this.n33;a.n34=this.n34;a.n41=this.n41;a.n42=this.n42;a.n43=this.n43;a.n44=this.n44;return a},flatten:function(){var a=this.flat;a[0]=this.n11;
a[1]=this.n21;a[2]=this.n31;a[3]=this.n41;a[4]=this.n12;a[5]=this.n22;a[6]=this.n32;a[7]=this.n42;a[8]=this.n13;a[9]=this.n23;a[10]=this.n33;a[11]=this.n43;a[12]=this.n14;a[13]=this.n24;a[14]=this.n34;a[15]=this.n44;return a},setTranslation:function(a,b,c){this.set(1,0,0,a,0,1,0,b,0,0,1,c,0,0,0,1);return this},setScale:function(a,b,c){this.set(a,0,0,0,0,b,0,0,0,0,c,0,0,0,0,1);return this},setRotX:function(a){var b=Math.cos(a);a=Math.sin(a);this.set(1,0,0,0,0,b,-a,0,0,a,b,0,0,0,0,1);return this},setRotY:function(a){var b=
Math.cos(a);a=Math.sin(a);this.set(b,0,a,0,0,1,0,0,-a,0,b,0,0,0,0,1);return this},setRotZ:function(a){var b=Math.cos(a);a=Math.sin(a);this.set(b,-a,0,0,a,b,0,0,0,0,1,0,0,0,0,1);return this},setRotAxis:function(a,b){var c=Math.cos(b),d=Math.sin(b),e=1-c,f=a.x,i=a.y,j=a.z,g=e*f,h=e*i;this.set(g*f+c,g*i-d*j,g*j+d*i,0,g*i+d*j,h*i+c,h*j-d*f,0,g*j-d*i,h*j+d*f,e*j*j+c,0,0,0,0,1);return this},toString:function(){return"| "+this.n11+" "+this.n12+" "+this.n13+" "+this.n14+" |\n| "+this.n21+" "+this.n22+" "+
this.n23+" "+this.n24+" |\n| "+this.n31+" "+this.n32+" "+this.n33+" "+this.n34+" |\n| "+this.n41+" "+this.n42+" "+this.n43+" "+this.n44+" |"}};THREE.Matrix4.translationMatrix=function(a,b,c){var d=new THREE.Matrix4;d.setTranslation(a,b,c);return d};THREE.Matrix4.scaleMatrix=function(a,b,c){var d=new THREE.Matrix4;d.setScale(a,b,c);return d};THREE.Matrix4.rotationXMatrix=function(a){var b=new THREE.Matrix4;b.setRotX(a);return b};
THREE.Matrix4.rotationYMatrix=function(a){var b=new THREE.Matrix4;b.setRotY(a);return b};THREE.Matrix4.rotationZMatrix=function(a){var b=new THREE.Matrix4;b.setRotZ(a);return b};THREE.Matrix4.rotationAxisAngleMatrix=function(a,b){var c=new THREE.Matrix4;c.setRotAxis(a,b);return c};
THREE.Matrix4.makeInvert=function(a){var b=a.n11,c=a.n12,d=a.n13,e=a.n14,f=a.n21,i=a.n22,j=a.n23,g=a.n24,h=a.n31,p=a.n32,m=a.n33,n=a.n34,q=a.n41,u=a.n42,v=a.n43,r=a.n44,k=new THREE.Matrix4;k.n11=j*n*u-g*m*u+g*p*v-i*n*v-j*p*r+i*m*r;k.n12=e*m*u-d*n*u-e*p*v+c*n*v+d*p*r-c*m*r;k.n13=d*g*u-e*j*u+e*i*v-c*g*v-d*i*r+c*j*r;k.n14=e*j*p-d*g*p-e*i*m+c*g*m+d*i*n-c*j*n;k.n21=g*m*q-j*n*q-g*h*v+f*n*v+j*h*r-f*m*r;k.n22=d*n*q-e*m*q+e*h*v-b*n*v-d*h*r+b*m*r;k.n23=e*j*q-d*g*q-e*f*v+b*g*v+d*f*r-b*j*r;k.n24=d*g*h-e*j*h+
e*f*m-b*g*m-d*f*n+b*j*n;k.n31=i*n*q-g*p*q+g*h*u-f*n*u-i*h*r+f*p*r;k.n32=e*p*q-c*n*q-e*h*u+b*n*u+c*h*r-b*p*r;k.n33=d*g*q-e*i*q+e*f*u-b*g*u-c*f*r+b*i*r;k.n34=e*i*h-c*g*h-e*f*p+b*g*p+c*f*n-b*i*n;k.n41=j*p*q-i*m*q-j*h*u+f*m*u+i*h*v-f*p*v;k.n42=c*m*q-d*p*q+d*h*u-b*m*u-c*h*v+b*p*v;k.n43=d*i*q-c*j*q-d*f*u+b*j*u+c*f*v-b*i*v;k.n44=c*j*h-d*i*h+d*f*p-b*j*p-c*f*m+b*i*m;k.multiplyScalar(1/a.determinant());return k};
THREE.Matrix4.makeInvert3x3=function(a){var b=a.flatten();a=a.m33;var c=a.m,d=b[10]*b[5]-b[6]*b[9],e=-b[10]*b[1]+b[2]*b[9],f=b[6]*b[1]-b[2]*b[5],i=-b[10]*b[4]+b[6]*b[8],j=b[10]*b[0]-b[2]*b[8],g=-b[6]*b[0]+b[2]*b[4],h=b[9]*b[4]-b[5]*b[8],p=-b[9]*b[0]+b[1]*b[8],m=b[5]*b[0]-b[1]*b[4];b=b[0]*d+b[1]*i+b[2]*h;if(b==0)throw"matrix not invertible";b=1/b;c[0]=b*d;c[1]=b*e;c[2]=b*f;c[3]=b*i;c[4]=b*j;c[5]=b*g;c[6]=b*h;c[7]=b*p;c[8]=b*m;return a};
THREE.Matrix4.makeFrustum=function(a,b,c,d,e,f){var i,j,g;i=new THREE.Matrix4;j=2*e/(b-a);g=2*e/(d-c);a=(b+a)/(b-a);c=(d+c)/(d-c);d=-(f+e)/(f-e);e=-2*f*e/(f-e);i.n11=j;i.n12=0;i.n13=a;i.n14=0;i.n21=0;i.n22=g;i.n23=c;i.n24=0;i.n31=0;i.n32=0;i.n33=d;i.n34=e;i.n41=0;i.n42=0;i.n43=-1;i.n44=0;return i};THREE.Matrix4.makePerspective=function(a,b,c,d){var e;a=c*Math.tan(a*Math.PI/360);e=-a;return THREE.Matrix4.makeFrustum(e*b,a*b,e,a,c,d)};
THREE.Matrix4.makeOrtho=function(a,b,c,d,e,f){var i,j,g,h;i=new THREE.Matrix4;j=b-a;g=c-d;h=f-e;a=(b+a)/j;c=(c+d)/g;e=(f+e)/h;i.n11=2/j;i.n12=0;i.n13=0;i.n14=-a;i.n21=0;i.n22=2/g;i.n23=0;i.n24=-c;i.n31=0;i.n32=0;i.n33=-2/h;i.n34=-e;i.n41=0;i.n42=0;i.n43=0;i.n44=1;return i};THREE.Matrix4.__tmpVec1=new THREE.Vector3;THREE.Matrix4.__tmpVec2=new THREE.Vector3;THREE.Matrix4.__tmpVec3=new THREE.Vector3;
THREE.Vertex=function(a,b){this.position=a||new THREE.Vector3;this.positionWorld=new THREE.Vector3;this.positionScreen=new THREE.Vector4;this.normal=b||new THREE.Vector3;this.normalWorld=new THREE.Vector3;this.normalScreen=new THREE.Vector3;this.tangent=new THREE.Vector4;this.__visible=true};THREE.Vertex.prototype={toString:function(){return"THREE.Vertex ( position: "+this.position+", normal: "+this.normal+" )"}};
THREE.Face3=function(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.centroid=new THREE.Vector3;this.normal=d instanceof THREE.Vector3?d:new THREE.Vector3;this.vertexNormals=d instanceof Array?d:[];this.materials=e instanceof Array?e:[e]};THREE.Face3.prototype={toString:function(){return"THREE.Face3 ( "+this.a+", "+this.b+", "+this.c+" )"}};
THREE.Face4=function(a,b,c,d,e,f){this.a=a;this.b=b;this.c=c;this.d=d;this.centroid=new THREE.Vector3;this.normal=e instanceof THREE.Vector3?e:new THREE.Vector3;this.vertexNormals=e instanceof Array?e:[];this.materials=f instanceof Array?f:[f]};THREE.Face4.prototype={toString:function(){return"THREE.Face4 ( "+this.a+", "+this.b+", "+this.c+" "+this.d+" )"}};THREE.UV=function(a,b){this.u=a||0;this.v=b||0};
THREE.UV.prototype={copy:function(a){this.u=a.u;this.v=a.v},toString:function(){return"THREE.UV ("+this.u+", "+this.v+")"}};THREE.Geometry=function(){this.vertices=[];this.faces=[];this.uvs=[];this.boundingSphere=this.boundingBox=null;this.geometryChunks={};this.hasTangents=false};
THREE.Geometry.prototype={computeCentroids:function(){var a,b,c;a=0;for(b=this.faces.length;a<b;a++){c=this.faces[a];c.centroid.set(0,0,0);if(c instanceof THREE.Face3){c.centroid.addSelf(this.vertices[c.a].position);c.centroid.addSelf(this.vertices[c.b].position);c.centroid.addSelf(this.vertices[c.c].position);c.centroid.divideScalar(3)}else if(c instanceof THREE.Face4){c.centroid.addSelf(this.vertices[c.a].position);c.centroid.addSelf(this.vertices[c.b].position);c.centroid.addSelf(this.vertices[c.c].position);
c.centroid.addSelf(this.vertices[c.d].position);c.centroid.divideScalar(4)}}},computeFaceNormals:function(a){var b,c,d,e,f,i,j=new THREE.Vector3,g=new THREE.Vector3;d=0;for(e=this.vertices.length;d<e;d++){f=this.vertices[d];f.normal.set(0,0,0)}d=0;for(e=this.faces.length;d<e;d++){f=this.faces[d];if(a&&f.vertexNormals.length){j.set(0,0,0);b=0;for(c=f.normal.length;b<c;b++)j.addSelf(f.vertexNormals[b]);j.divideScalar(3)}else{b=this.vertices[f.a];c=this.vertices[f.b];i=this.vertices[f.c];j.sub(i.position,
c.position);g.sub(b.position,c.position);j.crossSelf(g)}j.isZero()||j.normalize();f.normal.copy(j)}},computeVertexNormals:function(){var a,b,c,d;if(this.__tmpVertices==undefined){d=this.__tmpVertices=Array(this.vertices.length);a=0;for(b=this.vertices.length;a<b;a++)d[a]=new THREE.Vector3;a=0;for(b=this.faces.length;a<b;a++){c=this.faces[a];if(c instanceof THREE.Face3)c.vertexNormals=[new THREE.Vector3,new THREE.Vector3,new THREE.Vector3];else if(c instanceof THREE.Face4)c.vertexNormals=[new THREE.Vector3,
new THREE.Vector3,new THREE.Vector3,new THREE.Vector3]}}else{d=this.__tmpVertices;a=0;for(b=this.vertices.length;a<b;a++)d[a].set(0,0,0)}a=0;for(b=this.faces.length;a<b;a++){c=this.faces[a];if(c instanceof THREE.Face3){d[c.a].addSelf(c.normal);d[c.b].addSelf(c.normal);d[c.c].addSelf(c.normal)}else if(c instanceof THREE.Face4){d[c.a].addSelf(c.normal);d[c.b].addSelf(c.normal);d[c.c].addSelf(c.normal);d[c.d].addSelf(c.normal)}}a=0;for(b=this.vertices.length;a<b;a++)d[a].normalize();a=0;for(b=this.faces.length;a<
b;a++){c=this.faces[a];if(c instanceof THREE.Face3){c.vertexNormals[0].copy(d[c.a]);c.vertexNormals[1].copy(d[c.b]);c.vertexNormals[2].copy(d[c.c])}else if(c instanceof THREE.Face4){c.vertexNormals[0].copy(d[c.a]);c.vertexNormals[1].copy(d[c.b]);c.vertexNormals[2].copy(d[c.c]);c.vertexNormals[3].copy(d[c.d])}}},computeTangents:function(){function a(B,t,Q,w,N,ga,H){f=B.vertices[t].position;i=B.vertices[Q].position;j=B.vertices[w].position;g=e[N];h=e[ga];p=e[H];m=i.x-f.x;n=j.x-f.x;q=i.y-f.y;u=j.y-f.y;
v=i.z-f.z;r=j.z-f.z;k=h.u-g.u;E=p.u-g.u;C=h.v-g.v;K=p.v-g.v;I=1/(k*K-E*C);z.set((K*m-C*n)*I,(K*q-C*u)*I,(K*v-C*r)*I);L.set((k*n-E*m)*I,(k*u-E*q)*I,(k*r-E*v)*I);P[t].addSelf(z);P[Q].addSelf(z);P[w].addSelf(z);D[t].addSelf(L);D[Q].addSelf(L);D[w].addSelf(L)}var b,c,d,e,f,i,j,g,h,p,m,n,q,u,v,r,k,E,C,K,I,P=[],D=[],z=new THREE.Vector3,L=new THREE.Vector3,A=new THREE.Vector3,J=new THREE.Vector3,x=new THREE.Vector3;b=0;for(c=this.vertices.length;b<c;b++){P[b]=new THREE.Vector3;D[b]=new THREE.Vector3}b=0;
for(c=this.faces.length;b<c;b++){d=this.faces[b];e=this.uvs[b];if(d instanceof THREE.Face3){a(this,d.a,d.b,d.c,0,1,2);this.vertices[d.a].normal.copy(d.vertexNormals[0]);this.vertices[d.b].normal.copy(d.vertexNormals[1]);this.vertices[d.c].normal.copy(d.vertexNormals[2])}else if(d instanceof THREE.Face4){a(this,d.a,d.b,d.c,0,1,2);a(this,d.a,d.b,d.d,0,1,3);this.vertices[d.a].normal.copy(d.vertexNormals[0]);this.vertices[d.b].normal.copy(d.vertexNormals[1]);this.vertices[d.c].normal.copy(d.vertexNormals[2]);
this.vertices[d.d].normal.copy(d.vertexNormals[3])}}b=0;for(c=this.vertices.length;b<c;b++){x.copy(this.vertices[b].normal);d=P[b];A.copy(d);A.subSelf(x.multiplyScalar(x.dot(d))).normalize();J.cross(this.vertices[b].normal,d);d=J.dot(D[b]);d=d<0?-1:1;this.vertices[b].tangent.set(A.x,A.y,A.z,d)}this.hasTangents=true},computeBoundingBox:function(){var a;if(this.vertices.length>0){this.boundingBox={x:[this.vertices[0].position.x,this.vertices[0].position.x],y:[this.vertices[0].position.y,this.vertices[0].position.y],
z:[this.vertices[0].position.z,this.vertices[0].position.z]};for(var b=1,c=this.vertices.length;b<c;b++){a=this.vertices[b];if(a.position.x<this.boundingBox.x[0])this.boundingBox.x[0]=a.position.x;else if(a.position.x>this.boundingBox.x[1])this.boundingBox.x[1]=a.position.x;if(a.position.y<this.boundingBox.y[0])this.boundingBox.y[0]=a.position.y;else if(a.position.y>this.boundingBox.y[1])this.boundingBox.y[1]=a.position.y;if(a.position.z<this.boundingBox.z[0])this.boundingBox.z[0]=a.position.z;else if(a.position.z>
this.boundingBox.z[1])this.boundingBox.z[1]=a.position.z}}},computeBoundingSphere:function(){for(var a=this.boundingSphere===null?0:this.boundingSphere.radius,b=0,c=this.vertices.length;b<c;b++)a=Math.max(a,this.vertices[b].position.length());this.boundingSphere={radius:a}},sortFacesByMaterial:function(){function a(p){var m=[];b=0;for(c=p.length;b<c;b++)p[b]==undefined?m.push("undefined"):m.push(p[b].toString());return m.join("_")}var b,c,d,e,f,i,j,g,h={};d=0;for(e=this.faces.length;d<e;d++){f=this.faces[d];
i=f.materials;j=a(i);if(h[j]==undefined)h[j]={hash:j,counter:0};g=h[j].hash+"_"+h[j].counter;if(this.geometryChunks[g]==undefined)this.geometryChunks[g]={faces:[],materials:i,vertices:0};f=f instanceof THREE.Face3?3:4;if(this.geometryChunks[g].vertices+f>65535){h[j].counter+=1;g=h[j].hash+"_"+h[j].counter;if(this.geometryChunks[g]==undefined)this.geometryChunks[g]={faces:[],materials:i,vertices:0}}this.geometryChunks[g].faces.push(d);this.geometryChunks[g].vertices+=f}},toString:function(){return"THREE.Geometry ( vertices: "+
this.vertices+", faces: "+this.faces+", uvs: "+this.uvs+" )"}};
THREE.Camera=function(a,b,c,d){this.fov=a;this.aspect=b;this.near=c;this.far=d;this.position=new THREE.Vector3;this.target={position:new THREE.Vector3};this.autoUpdateMatrix=true;this.projectionMatrix=null;this.matrix=new THREE.Matrix4;this.up=new THREE.Vector3(0,1,0);this.tmpVec=new THREE.Vector3;this.translateX=function(e){this.tmpVec.sub(this.target.position,this.position).normalize().multiplyScalar(e);this.tmpVec.crossSelf(this.up);this.position.addSelf(this.tmpVec);this.target.position.addSelf(this.tmpVec)};
this.translateZ=function(e){this.tmpVec.sub(this.target.position,this.position).normalize().multiplyScalar(e);this.position.subSelf(this.tmpVec);this.target.position.subSelf(this.tmpVec)};this.updateMatrix=function(){this.matrix.lookAt(this.position,this.target.position,this.up)};this.updateProjectionMatrix=function(){this.projectionMatrix=THREE.Matrix4.makePerspective(this.fov,this.aspect,this.near,this.far)};this.updateProjectionMatrix()};
THREE.Camera.prototype={toString:function(){return"THREE.Camera ( "+this.position+", "+this.target.position+" )"}};THREE.Light=function(a){this.color=new THREE.Color(a)};THREE.AmbientLight=function(a){THREE.Light.call(this,a)};THREE.AmbientLight.prototype=new THREE.Light;THREE.AmbientLight.prototype.constructor=THREE.AmbientLight;THREE.DirectionalLight=function(a,b){THREE.Light.call(this,a);this.position=new THREE.Vector3(0,1,0);this.intensity=b||1};THREE.DirectionalLight.prototype=new THREE.Light;
THREE.DirectionalLight.prototype.constructor=THREE.DirectionalLight;THREE.PointLight=function(a,b){THREE.Light.call(this,a);this.position=new THREE.Vector3;this.intensity=b||1};THREE.PointLight.prototype=new THREE.Light;THREE.PointLight.prototype.constructor=THREE.PointLight;
THREE.Object3D=function(){this.id=THREE.Object3DCounter.value++;this.position=new THREE.Vector3;this.rotation=new THREE.Vector3;this.scale=new THREE.Vector3(1,1,1);this.matrix=new THREE.Matrix4;this.rotationMatrix=new THREE.Matrix4;this.tmpMatrix=new THREE.Matrix4;this.screen=new THREE.Vector3;this.visible=this.autoUpdateMatrix=true};
THREE.Object3D.prototype={updateMatrix:function(){var a=this.position,b=this.rotation,c=this.scale,d=this.tmpMatrix;this.matrix.setTranslation(a.x,a.y,a.z);this.rotationMatrix.setRotX(b.x);if(b.y!=0){d.setRotY(b.y);this.rotationMatrix.multiplySelf(d)}if(b.z!=0){d.setRotZ(b.z);this.rotationMatrix.multiplySelf(d)}this.matrix.multiplySelf(this.rotationMatrix);if(c.x!=0||c.y!=0||c.z!=0){d.setScale(c.x,c.y,c.z);this.matrix.multiplySelf(d)}}};THREE.Object3DCounter={value:0};
THREE.Particle=function(a){THREE.Object3D.call(this);this.materials=a instanceof Array?a:[a];this.autoUpdateMatrix=false};THREE.Particle.prototype=new THREE.Object3D;THREE.Particle.prototype.constructor=THREE.Particle;THREE.Line=function(a,b,c){THREE.Object3D.call(this);this.geometry=a;this.materials=b instanceof Array?b:[b];this.type=c!=undefined?c:THREE.LineStrip};THREE.LineStrip=0;THREE.LinePieces=1;THREE.Line.prototype=new THREE.Object3D;THREE.Line.prototype.constructor=THREE.Line;
THREE.Mesh=function(a,b){THREE.Object3D.call(this);this.geometry=a;this.materials=b instanceof Array?b:[b];this.overdraw=this.doubleSided=this.flipSided=false;this.geometry.boundingSphere||this.geometry.computeBoundingSphere()};THREE.Mesh.prototype=new THREE.Object3D;THREE.Mesh.prototype.constructor=THREE.Mesh;THREE.FlatShading=0;THREE.SmoothShading=1;THREE.NormalBlending=0;THREE.AdditiveBlending=1;THREE.SubtractiveBlending=2;
THREE.LineBasicMaterial=function(a){this.color=new THREE.Color(16777215);this.opacity=1;this.blending=THREE.NormalBlending;this.linewidth=1;this.linejoin=this.linecap="round";if(a){a.color!==undefined&&this.color.setHex(a.color);if(a.opacity!==undefined)this.opacity=a.opacity;if(a.blending!==undefined)this.blending=a.blending;if(a.linewidth!==undefined)this.linewidth=a.linewidth;if(a.linecap!==undefined)this.linecap=a.linecap;if(a.linejoin!==undefined)this.linejoin=a.linejoin}};
THREE.LineBasicMaterial.prototype={toString:function(){return"THREE.LineBasicMaterial (<br/>color: "+this.color+"<br/>opacity: "+this.opacity+"<br/>blending: "+this.blending+"<br/>linewidth: "+this.linewidth+"<br/>linecap: "+this.linecap+"<br/>linejoin: "+this.linejoin+"<br/>)"}};
THREE.MeshBasicMaterial=function(a){this.id=THREE.MeshBasicMaterialCounter.value++;this.color=new THREE.Color(16777215);this.env_map=this.map=null;this.combine=THREE.MultiplyOperation;this.reflectivity=1;this.refraction_ratio=0.98;this.fog=true;this.opacity=1;this.shading=THREE.SmoothShading;this.blending=THREE.NormalBlending;this.wireframe=false;this.wireframe_linewidth=1;this.wireframe_linejoin=this.wireframe_linecap="round";if(a){a.color!==undefined&&this.color.setHex(a.color);if(a.map!==undefined)this.map=
a.map;if(a.env_map!==undefined)this.env_map=a.env_map;if(a.combine!==undefined)this.combine=a.combine;if(a.reflectivity!==undefined)this.reflectivity=a.reflectivity;if(a.refraction_ratio!==undefined)this.refraction_ratio=a.refraction_ratio;if(a.fog!==undefined)this.fog=a.fog;if(a.opacity!==undefined)this.opacity=a.opacity;if(a.shading!==undefined)this.shading=a.shading;if(a.blending!==undefined)this.blending=a.blending;if(a.wireframe!==undefined)this.wireframe=a.wireframe;if(a.wireframe_linewidth!==
undefined)this.wireframe_linewidth=a.wireframe_linewidth;if(a.wireframe_linecap!==undefined)this.wireframe_linecap=a.wireframe_linecap;if(a.wireframe_linejoin!==undefined)this.wireframe_linejoin=a.wireframe_linejoin}};
THREE.MeshBasicMaterial.prototype={toString:function(){return"THREE.MeshBasicMaterial (<br/>id: "+this.id+"<br/>color: "+this.color+"<br/>map: "+this.map+"<br/>env_map: "+this.env_map+"<br/>combine: "+this.combine+"<br/>reflectivity: "+this.reflectivity+"<br/>refraction_ratio: "+this.refraction_ratio+"<br/>opacity: "+this.opacity+"<br/>blending: "+this.blending+"<br/>wireframe: "+this.wireframe+"<br/>wireframe_linewidth: "+this.wireframe_linewidth+"<br/>wireframe_linecap: "+this.wireframe_linecap+
"<br/>wireframe_linejoin: "+this.wireframe_linejoin+"<br/>)"}};THREE.MeshBasicMaterialCounter={value:0};
THREE.MeshLambertMaterial=function(a){this.id=THREE.MeshLambertMaterialCounter.value++;this.color=new THREE.Color(16777215);this.env_map=this.map=null;this.combine=THREE.MultiplyOperation;this.reflectivity=1;this.refraction_ratio=0.98;this.fog=true;this.opacity=1;this.shading=THREE.SmoothShading;this.blending=THREE.NormalBlending;this.wireframe=false;this.wireframe_linewidth=1;this.wireframe_linejoin=this.wireframe_linecap="round";if(a){a.color!==undefined&&this.color.setHex(a.color);if(a.map!==undefined)this.map=
a.map;if(a.env_map!==undefined)this.env_map=a.env_map;if(a.combine!==undefined)this.combine=a.combine;if(a.reflectivity!==undefined)this.reflectivity=a.reflectivity;if(a.refraction_ratio!==undefined)this.refraction_ratio=a.refraction_ratio;if(a.fog!==undefined)this.fog=a.fog;if(a.opacity!==undefined)this.opacity=a.opacity;if(a.shading!==undefined)this.shading=a.shading;if(a.blending!==undefined)this.blending=a.blending;if(a.wireframe!==undefined)this.wireframe=a.wireframe;if(a.wireframe_linewidth!==
undefined)this.wireframe_linewidth=a.wireframe_linewidth;if(a.wireframe_linecap!==undefined)this.wireframe_linecap=a.wireframe_linecap;if(a.wireframe_linejoin!==undefined)this.wireframe_linejoin=a.wireframe_linejoin}};
THREE.MeshLambertMaterial.prototype={toString:function(){return"THREE.MeshLambertMaterial (<br/>id: "+this.id+"<br/>color: "+this.color+"<br/>map: "+this.map+"<br/>env_map: "+this.env_map+"<br/>combine: "+this.combine+"<br/>reflectivity: "+this.reflectivity+"<br/>refraction_ratio: "+this.refraction_ratio+"<br/>opacity: "+this.opacity+"<br/>shading: "+this.shading+"<br/>blending: "+this.blending+"<br/>wireframe: "+this.wireframe+"<br/>wireframe_linewidth: "+this.wireframe_linewidth+"<br/>wireframe_linecap: "+
this.wireframe_linecap+"<br/>wireframe_linejoin: "+this.wireframe_linejoin+"<br/> )"}};THREE.MeshLambertMaterialCounter={value:0};
THREE.MeshPhongMaterial=function(a){this.id=THREE.MeshPhongMaterialCounter.value++;this.color=new THREE.Color(16777215);this.ambient=new THREE.Color(328965);this.specular=new THREE.Color(1118481);this.shininess=30;this.env_map=this.specular_map=this.map=null;this.combine=THREE.MultiplyOperation;this.reflectivity=1;this.refraction_ratio=0.98;this.fog=true;this.opacity=1;this.shading=THREE.SmoothShading;this.blending=THREE.NormalBlending;this.wireframe=false;this.wireframe_linewidth=1;this.wireframe_linejoin=
this.wireframe_linecap="round";if(a){if(a.color!==undefined)this.color=new THREE.Color(a.color);if(a.ambient!==undefined)this.ambient=new THREE.Color(a.ambient);if(a.specular!==undefined)this.specular=new THREE.Color(a.specular);if(a.shininess!==undefined)this.shininess=a.shininess;if(a.map!==undefined)this.map=a.map;if(a.specular_map!==undefined)this.specular_map=a.specular_map;if(a.env_map!==undefined)this.env_map=a.env_map;if(a.combine!==undefined)this.combine=a.combine;if(a.reflectivity!==undefined)this.reflectivity=
a.reflectivity;if(a.refraction_ratio!==undefined)this.refraction_ratio=a.refraction_ratio;if(a.fog!==undefined)this.fog=a.fog;if(a.opacity!==undefined)this.opacity=a.opacity;if(a.shading!==undefined)this.shading=a.shading;if(a.blending!==undefined)this.blending=a.blending;if(a.wireframe!==undefined)this.wireframe=a.wireframe;if(a.wireframe_linewidth!==undefined)this.wireframe_linewidth=a.wireframe_linewidth;if(a.wireframe_linecap!==undefined)this.wireframe_linecap=a.wireframe_linecap;if(a.wireframe_linejoin!==
undefined)this.wireframe_linejoin=a.wireframe_linejoin}};
THREE.MeshPhongMaterial.prototype={toString:function(){return"THREE.MeshPhongMaterial (<br/>id: "+this.id+"<br/>color: "+this.color+"<br/>ambient: "+this.ambient+"<br/>specular: "+this.specular+"<br/>shininess: "+this.shininess+"<br/>map: "+this.map+"<br/>specular_map: "+this.specular_map+"<br/>env_map: "+this.env_map+"<br/>combine: "+this.combine+"<br/>reflectivity: "+this.reflectivity+"<br/>refraction_ratio: "+this.refraction_ratio+"<br/>opacity: "+this.opacity+"<br/>shading: "+this.shading+"<br/>wireframe: "+
this.wireframe+"<br/>wireframe_linewidth: "+this.wireframe_linewidth+"<br/>wireframe_linecap: "+this.wireframe_linecap+"<br/>wireframe_linejoin: "+this.wireframe_linejoin+"<br/>)"}};THREE.MeshPhongMaterialCounter={value:0};
THREE.MeshDepthMaterial=function(a){this.opacity=1;this.shading=THREE.SmoothShading;this.blending=THREE.NormalBlending;this.wireframe=false;this.wireframe_linewidth=1;this.wireframe_linejoin=this.wireframe_linecap="round";if(a){if(a.opacity!==undefined)this.opacity=a.opacity;if(a.blending!==undefined)this.blending=a.blending}};THREE.MeshDepthMaterial.prototype={toString:function(){return"THREE.MeshDepthMaterial"}};
THREE.MeshNormalMaterial=function(a){this.opacity=1;this.shading=THREE.FlatShading;this.blending=THREE.NormalBlending;if(a){if(a.opacity!==undefined)this.opacity=a.opacity;if(a.shading!==undefined)this.shading=a.shading;if(a.blending!==undefined)this.blending=a.blending}};THREE.MeshNormalMaterial.prototype={toString:function(){return"THREE.MeshNormalMaterial"}};THREE.MeshFaceMaterial=function(){};THREE.MeshFaceMaterial.prototype={toString:function(){return"THREE.MeshFaceMaterial"}};
THREE.ParticleBasicMaterial=function(a){this.color=new THREE.Color(16777215);this.map=null;this.opacity=1;this.blending=THREE.NormalBlending;this.offset=new THREE.Vector2;if(a){a.color!==undefined&&this.color.setHex(a.color);if(a.map!==undefined)this.map=a.map;if(a.opacity!==undefined)this.opacity=a.opacity;if(a.blending!==undefined)this.blending=a.blending}};
THREE.ParticleBasicMaterial.prototype={toString:function(){return"THREE.ParticleBasicMaterial (<br/>color: "+this.color+"<br/>map: "+this.map+"<br/>opacity: "+this.opacity+"<br/>blending: "+this.blending+"<br/>)"}};THREE.ParticleCircleMaterial=function(a){this.color=new THREE.Color(16777215);this.opacity=1;this.blending=THREE.NormalBlending;if(a){a.color!==undefined&&this.color.setHex(a.color);if(a.opacity!==undefined)this.opacity=a.opacity;if(a.blending!==undefined)this.blending=a.blending}};
THREE.ParticleCircleMaterial.prototype={toString:function(){return"THREE.ParticleCircleMaterial (<br/>color: "+this.color+"<br/>opacity: "+this.opacity+"<br/>blending: "+this.blending+"<br/>)"}};THREE.Texture=function(a,b,c,d,e,f){this.image=a;this.mapping=b!==undefined?b:new THREE.UVMapping;this.wrap_s=c!==undefined?c:THREE.ClampToEdgeWrapping;this.wrap_t=d!==undefined?d:THREE.ClampToEdgeWrapping;this.mag_filter=e!==undefined?e:THREE.LinearFilter;this.min_filter=f!==undefined?f:THREE.LinearMipMapLinearFilter};
THREE.Texture.prototype={clone:function(){return new THREE.Texture(this.image,this.mapping,this.wrap_s,this.wrap_t,this.mag_filter,this.min_filter)},toString:function(){return"THREE.Texture (<br/>image: "+this.image+"<br/>wrap_s: "+this.wrap_s+"<br/>wrap_t: "+this.wrap_t+"<br/>mag_filter: "+this.mag_filter+"<br/>min_filter: "+this.min_filter+"<br/>)"}};THREE.MultiplyOperation=0;THREE.MixOperation=1;THREE.RepeatWrapping=0;THREE.ClampToEdgeWrapping=1;THREE.MirroredRepeatWrapping=2;
THREE.NearestFilter=3;THREE.NearestMipMapNearestFilter=4;THREE.NearestMipMapLinearFilter=5;THREE.LinearFilter=6;THREE.LinearMipMapNearestFilter=7;THREE.LinearMipMapLinearFilter=8;THREE.ByteType=9;THREE.UnsignedByteType=10;THREE.ShortType=11;THREE.UnsignedShortType=12;THREE.IntType=13;THREE.UnsignedIntType=14;THREE.FloatType=15;THREE.AlphaFormat=16;THREE.RGBFormat=17;THREE.RGBAFormat=18;THREE.LuminanceFormat=19;THREE.LuminanceAlphaFormat=20;THREE.CubeReflectionMapping=function(){};
THREE.CubeRefractionMapping=function(){};THREE.LatitudeReflectionMapping=function(){};THREE.LatitudeRefractionMapping=function(){};THREE.SphericalReflectionMapping=function(){};THREE.SphericalRefractionMapping=function(){};THREE.UVMapping=function(){};
THREE.Scene=function(){this.objects=[];this.lights=[];this.fog=null;this.addObject=function(a){this.objects.indexOf(a)===-1&&this.objects.push(a)};this.removeObject=function(a){a=this.objects.indexOf(a);a!==-1&&this.objects.splice(a,1)};this.addLight=function(a){this.lights.indexOf(a)===-1&&this.lights.push(a)};this.removeLight=function(a){a=this.lights.indexOf(a);a!==-1&&this.lights.splice(a,1)};this.toString=function(){return"THREE.Scene ( "+this.objects+" )"}};
THREE.Projector=function(){function a(D,z){return z.z-D.z}function b(D,z){var L=0,A=1,J=D.z+D.w,x=z.z+z.w,B=-D.z+D.w,t=-z.z+z.w;if(J>=0&&x>=0&&B>=0&&t>=0)return true;else if(J<0&&x<0||B<0&&t<0)return false;else{if(J<0)L=Math.max(L,J/(J-x));else if(x<0)A=Math.min(A,J/(J-x));if(B<0)L=Math.max(L,B/(B-t));else if(t<0)A=Math.min(A,B/(B-t));if(A<L)return false;else{D.lerpSelf(z,L);z.lerpSelf(D,1-A);return true}}}var c,d,e=[],f,i,j,g=[],h,p,m=[],n,q,u=[],v=new THREE.Vector4,r=new THREE.Vector4,k=new THREE.Matrix4,
E=new THREE.Matrix4,C=[],K=new THREE.Vector4,I=new THREE.Vector4,P;this.projectObjects=function(D,z,L){var A=[],J,x;d=0;k.multiply(z.projectionMatrix,z.matrix);C[0]=new THREE.Vector4(k.n41-k.n11,k.n42-k.n12,k.n43-k.n13,k.n44-k.n14);C[1]=new THREE.Vector4(k.n41+k.n11,k.n42+k.n12,k.n43+k.n13,k.n44+k.n14);C[2]=new THREE.Vector4(k.n41+k.n21,k.n42+k.n22,k.n43+k.n23,k.n44+k.n24);C[3]=new THREE.Vector4(k.n41-k.n21,k.n42-k.n22,k.n43-k.n23,k.n44-k.n24);C[4]=new THREE.Vector4(k.n41-k.n31,k.n42-k.n32,k.n43-
k.n33,k.n44-k.n34);C[5]=new THREE.Vector4(k.n41+k.n31,k.n42+k.n32,k.n43+k.n33,k.n44+k.n34);z=0;for(J=C.length;z<J;z++){x=C[z];x.divideScalar(Math.sqrt(x.x*x.x+x.y*x.y+x.z*x.z))}J=D.objects;D=0;for(z=J.length;D<z;D++){x=J[D];var B;if(!(B=!x.visible)){if(B=x instanceof THREE.Mesh){a:{B=void 0;for(var t=x.position,Q=-x.geometry.boundingSphere.radius*Math.max(x.scale.x,Math.max(x.scale.y,x.scale.z)),w=0;w<6;w++){B=C[w].x*t.x+C[w].y*t.y+C[w].z*t.z+C[w].w;if(B<=Q){B=false;break a}}B=true}B=!B}B=B}if(!B){c=
e[d]=e[d]||new THREE.RenderableObject;v.copy(x.position);k.multiplyVector3(v);c.object=x;c.z=v.z;A.push(c);d++}}L&&A.sort(a);return A};this.projectScene=function(D,z,L){var A=[],J=z.near,x=z.far,B,t,Q,w,N,ga,H,ha,ja,ka,la,Z,O,G,U,R;j=p=q=0;z.autoUpdateMatrix&&z.updateMatrix();k.multiply(z.projectionMatrix,z.matrix);ga=this.projectObjects(D,z,true);D=0;for(B=ga.length;D<B;D++){H=ga[D].object;if(H.visible){H.autoUpdateMatrix&&H.updateMatrix();ha=H.matrix;ja=H.rotationMatrix;ka=H.materials;la=H.overdraw;
if(H instanceof THREE.Mesh){Z=H.geometry;O=Z.vertices;t=0;for(Q=O.length;t<Q;t++){G=O[t];G.positionWorld.copy(G.position);ha.multiplyVector3(G.positionWorld);w=G.positionScreen;w.copy(G.positionWorld);k.multiplyVector4(w);w.x/=w.w;w.y/=w.w;G.__visible=w.z>J&&w.z<x}Z=Z.faces;t=0;for(Q=Z.length;t<Q;t++){G=Z[t];if(G instanceof THREE.Face3){w=O[G.a];N=O[G.b];U=O[G.c];if(w.__visible&&N.__visible&&U.__visible)if(H.doubleSided||H.flipSided!=(U.positionScreen.x-w.positionScreen.x)*(N.positionScreen.y-w.positionScreen.y)-
(U.positionScreen.y-w.positionScreen.y)*(N.positionScreen.x-w.positionScreen.x)<0){f=g[j]=g[j]||new THREE.RenderableFace3;f.v1.positionWorld.copy(w.positionWorld);f.v2.positionWorld.copy(N.positionWorld);f.v3.positionWorld.copy(U.positionWorld);f.v1.positionScreen.copy(w.positionScreen);f.v2.positionScreen.copy(N.positionScreen);f.v3.positionScreen.copy(U.positionScreen);f.normalWorld.copy(G.normal);ja.multiplyVector3(f.normalWorld);f.centroidWorld.copy(G.centroid);ha.multiplyVector3(f.centroidWorld);
f.centroidScreen.copy(f.centroidWorld);k.multiplyVector3(f.centroidScreen);U=G.vertexNormals;P=f.vertexNormalsWorld;w=0;for(N=U.length;w<N;w++){R=P[w]=P[w]||new THREE.Vector3;R.copy(U[w]);ja.multiplyVector3(R)}f.z=f.centroidScreen.z;f.meshMaterials=ka;f.faceMaterials=G.materials;f.overdraw=la;if(H.geometry.uvs[t]){f.uvs[0]=H.geometry.uvs[t][0];f.uvs[1]=H.geometry.uvs[t][1];f.uvs[2]=H.geometry.uvs[t][2]}A.push(f);j++}}else if(G instanceof THREE.Face4){w=O[G.a];N=O[G.b];U=O[G.c];R=O[G.d];if(w.__visible&&
N.__visible&&U.__visible&&R.__visible)if(H.doubleSided||H.flipSided!=((R.positionScreen.x-w.positionScreen.x)*(N.positionScreen.y-w.positionScreen.y)-(R.positionScreen.y-w.positionScreen.y)*(N.positionScreen.x-w.positionScreen.x)<0||(N.positionScreen.x-U.positionScreen.x)*(R.positionScreen.y-U.positionScreen.y)-(N.positionScreen.y-U.positionScreen.y)*(R.positionScreen.x-U.positionScreen.x)<0)){f=g[j]=g[j]||new THREE.RenderableFace3;f.v1.positionWorld.copy(w.positionWorld);f.v2.positionWorld.copy(N.positionWorld);
f.v3.positionWorld.copy(R.positionWorld);f.v1.positionScreen.copy(w.positionScreen);f.v2.positionScreen.copy(N.positionScreen);f.v3.positionScreen.copy(R.positionScreen);f.normalWorld.copy(G.normal);ja.multiplyVector3(f.normalWorld);f.centroidWorld.copy(G.centroid);ha.multiplyVector3(f.centroidWorld);f.centroidScreen.copy(f.centroidWorld);k.multiplyVector3(f.centroidScreen);f.z=f.centroidScreen.z;f.meshMaterials=ka;f.faceMaterials=G.materials;f.overdraw=la;if(H.geometry.uvs[t]){f.uvs[0]=H.geometry.uvs[t][0];
f.uvs[1]=H.geometry.uvs[t][1];f.uvs[2]=H.geometry.uvs[t][3]}A.push(f);j++;i=g[j]=g[j]||new THREE.RenderableFace3;i.v1.positionWorld.copy(N.positionWorld);i.v2.positionWorld.copy(U.positionWorld);i.v3.positionWorld.copy(R.positionWorld);i.v1.positionScreen.copy(N.positionScreen);i.v2.positionScreen.copy(U.positionScreen);i.v3.positionScreen.copy(R.positionScreen);i.normalWorld.copy(f.normalWorld);i.centroidWorld.copy(f.centroidWorld);i.centroidScreen.copy(f.centroidScreen);i.z=i.centroidScreen.z;i.meshMaterials=
ka;i.faceMaterials=G.materials;i.overdraw=la;if(H.geometry.uvs[t]){i.uvs[0]=H.geometry.uvs[t][1];i.uvs[1]=H.geometry.uvs[t][2];i.uvs[2]=H.geometry.uvs[t][3]}A.push(i);j++}}}}else if(H instanceof THREE.Line){E.multiply(k,ha);O=H.geometry.vertices;G=O[0];G.positionScreen.copy(G.position);E.multiplyVector4(G.positionScreen);t=1;for(Q=O.length;t<Q;t++){w=O[t];w.positionScreen.copy(w.position);E.multiplyVector4(w.positionScreen);N=O[t-1];K.copy(w.positionScreen);I.copy(N.positionScreen);if(b(K,I)){K.multiplyScalar(1/
K.w);I.multiplyScalar(1/I.w);h=m[p]=m[p]||new THREE.RenderableLine;h.v1.positionScreen.copy(K);h.v2.positionScreen.copy(I);h.z=Math.max(K.z,I.z);h.materials=H.materials;A.push(h);p++}}}else if(H instanceof THREE.Particle){r.set(H.position.x,H.position.y,H.position.z,1);k.multiplyVector4(r);r.z/=r.w;if(r.z>0&&r.z<1){n=u[q]=u[q]||new THREE.RenderableParticle;n.x=r.x/r.w;n.y=r.y/r.w;n.z=r.z;n.rotation=H.rotation.z;n.scale.x=H.scale.x*Math.abs(n.x-(r.x+z.projectionMatrix.n11)/(r.w+z.projectionMatrix.n14));
n.scale.y=H.scale.y*Math.abs(n.y-(r.y+z.projectionMatrix.n22)/(r.w+z.projectionMatrix.n24));n.materials=H.materials;A.push(n);q++}}}}L&&A.sort(a);return A};this.unprojectVector=function(D,z){var L=THREE.Matrix4.makeInvert(z.matrix);L.multiplySelf(THREE.Matrix4.makeInvert(z.projectionMatrix));L.multiplyVector3(D);return D}};
THREE.CanvasRenderer=function(){function a(W){if(n!=W)h.globalAlpha=n=W}function b(W){if(q!=W){switch(W){case THREE.NormalBlending:h.globalCompositeOperation="source-over";break;case THREE.AdditiveBlending:h.globalCompositeOperation="lighter";break;case THREE.SubtractiveBlending:h.globalCompositeOperation="darker"}q=W}}var c=null,d=new THREE.Projector,e=document.createElement("canvas"),f,i,j,g,h=e.getContext("2d"),p=new THREE.Color(0),m=0,n=1,q=0,u=null,v=null,r=1,k,E,C,K,I,P,D,z,L,A=new THREE.Color,
J=new THREE.Color,x=new THREE.Color,B=new THREE.Color,t=new THREE.Color,Q,w,N,ga,H,ha,ja,ka,la,Z=new THREE.Rectangle,O=new THREE.Rectangle,G=new THREE.Rectangle,U=false,R=new THREE.Color,$=new THREE.Color,ma=new THREE.Color,na=new THREE.Color,La=Math.PI*2,S=new THREE.Vector3,ra,sa,Ca,aa,ta,xa,pa=16;ra=document.createElement("canvas");ra.width=ra.height=2;sa=ra.getContext("2d");sa.fillStyle="rgba(0,0,0,1)";sa.fillRect(0,0,2,2);Ca=sa.getImageData(0,0,2,2);aa=Ca.data;ta=document.createElement("canvas");
ta.width=ta.height=pa;xa=ta.getContext("2d");xa.translate(-pa/2,-pa/2);xa.scale(pa,pa);pa--;this.domElement=e;this.sortElements=this.sortObjects=this.autoClear=true;this.setSize=function(W,ia){f=W;i=ia;j=f/2;g=i/2;e.width=f;e.height=i;Z.set(-j,-g,j,g);n=1;q=0;v=u=null;r=1};this.setClearColor=function(W,ia){p.setHex(W);m=ia;O.set(-j,-g,j,g);h.setTransform(1,0,0,-1,j,g);this.clear()};this.clear=function(){if(!O.isEmpty()){h.setTransform(1,0,0,-1,j,g);O.inflate(1);O.minSelf(Z);if(p.hex==0&&m==0)h.clearRect(O.getX(),
O.getY(),O.getWidth(),O.getHeight());else{b(THREE.NormalBlending);a(1);h.fillStyle="rgba("+Math.floor(p.r*255)+","+Math.floor(p.g*255)+","+Math.floor(p.b*255)+","+m+")";h.fillRect(O.getX(),O.getY(),O.getWidth(),O.getHeight())}O.empty()}};this.render=function(W,ia){function Ma(l){var F,y,o,s=l.lights;$.setRGB(0,0,0);ma.setRGB(0,0,0);na.setRGB(0,0,0);l=0;for(F=s.length;l<F;l++){y=s[l];o=y.color;if(y instanceof THREE.AmbientLight){$.r+=o.r;$.g+=o.g;$.b+=o.b}else if(y instanceof THREE.DirectionalLight){ma.r+=
o.r;ma.g+=o.g;ma.b+=o.b}else if(y instanceof THREE.PointLight){na.r+=o.r;na.g+=o.g;na.b+=o.b}}}function ya(l,F,y,o){var s,M,V,X,Y=l.lights;l=0;for(s=Y.length;l<s;l++){M=Y[l];V=M.color;X=M.intensity;if(M instanceof THREE.DirectionalLight){M=y.dot(M.position)*X;if(M>0){o.r+=V.r*M;o.g+=V.g*M;o.b+=V.b*M}}else if(M instanceof THREE.PointLight){S.sub(M.position,F);S.normalize();M=y.dot(S)*X;if(M>0){o.r+=V.r*M;o.g+=V.g*M;o.b+=V.b*M}}}}function Na(l,F,y){if(y.opacity!=0){a(y.opacity);b(y.blending);var o,
s,M,V,X,Y;if(y instanceof THREE.ParticleBasicMaterial){if(y.map&&y.map.image.loaded){V=y.map.image;X=V.width>>1;Y=V.height>>1;s=F.scale.x*j;M=F.scale.y*g;y=s*X;o=M*Y;G.set(l.x-y,l.y-o,l.x+y,l.y+o);if(Z.instersects(G)){h.save();h.translate(l.x,l.y);h.rotate(-F.rotation);h.scale(s,-M);h.translate(-X,-Y);h.drawImage(V,0,0);h.restore()}}}else if(y instanceof THREE.ParticleCircleMaterial){if(U){R.r=$.r+ma.r+na.r;R.g=$.g+ma.g+na.g;R.b=$.b+ma.b+na.b;A.r=y.color.r*R.r;A.g=y.color.g*R.g;A.b=y.color.b*R.b;
A.updateStyleString()}else A.__styleString=y.color.__styleString;y=F.scale.x*j;o=F.scale.y*g;G.set(l.x-y,l.y-o,l.x+y,l.y+o);if(Z.instersects(G)){s=A.__styleString;if(v!=s)h.fillStyle=v=s;h.save();h.translate(l.x,l.y);h.rotate(-F.rotation);h.scale(y,o);h.beginPath();h.arc(0,0,1,0,La,true);h.closePath();h.fill();h.restore()}}}}function Oa(l,F,y,o){if(o.opacity!=0){a(o.opacity);b(o.blending);h.beginPath();h.moveTo(l.positionScreen.x,l.positionScreen.y);h.lineTo(F.positionScreen.x,F.positionScreen.y);
h.closePath();if(o instanceof THREE.LineBasicMaterial){A.__styleString=o.color.__styleString;l=o.linewidth;if(r!=l)h.lineWidth=r=l;l=A.__styleString;if(u!=l)h.strokeStyle=u=l;h.stroke();G.inflate(o.linewidth*2)}}}function Ha(l,F,y,o,s,M){if(s.opacity!=0){a(s.opacity);b(s.blending);K=l.positionScreen.x;I=l.positionScreen.y;P=F.positionScreen.x;D=F.positionScreen.y;z=y.positionScreen.x;L=y.positionScreen.y;h.beginPath();h.moveTo(K,I);h.lineTo(P,D);h.lineTo(z,L);h.lineTo(K,I);h.closePath();if(s instanceof
THREE.MeshBasicMaterial)if(s.map)s.map.image.loaded&&s.map.mapping instanceof THREE.UVMapping&&ua(K,I,P,D,z,L,s.map.image,o.uvs[0].u,o.uvs[0].v,o.uvs[1].u,o.uvs[1].v,o.uvs[2].u,o.uvs[2].v);else if(s.env_map){if(s.env_map.image.loaded)if(s.env_map.mapping instanceof THREE.SphericalReflectionMapping){l=ia.matrix;S.copy(o.vertexNormalsWorld[0]);ga=(S.x*l.n11+S.y*l.n12+S.z*l.n13)*0.5+0.5;H=-(S.x*l.n21+S.y*l.n22+S.z*l.n23)*0.5+0.5;S.copy(o.vertexNormalsWorld[1]);ha=(S.x*l.n11+S.y*l.n12+S.z*l.n13)*0.5+
0.5;ja=-(S.x*l.n21+S.y*l.n22+S.z*l.n23)*0.5+0.5;S.copy(o.vertexNormalsWorld[2]);ka=(S.x*l.n11+S.y*l.n12+S.z*l.n13)*0.5+0.5;la=-(S.x*l.n21+S.y*l.n22+S.z*l.n23)*0.5+0.5;ua(K,I,P,D,z,L,s.env_map.image,ga,H,ha,ja,ka,la)}}else s.wireframe?za(s.color.__styleString,s.wireframe_linewidth):Aa(s.color.__styleString);else if(s instanceof THREE.MeshLambertMaterial){if(s.map&&!s.wireframe){s.map.mapping instanceof THREE.UVMapping&&ua(K,I,P,D,z,L,s.map.image,o.uvs[0].u,o.uvs[0].v,o.uvs[1].u,o.uvs[1].v,o.uvs[2].u,
o.uvs[2].v);b(THREE.SubtractiveBlending)}if(U)if(!s.wireframe&&s.shading==THREE.SmoothShading&&o.vertexNormalsWorld.length==3){J.r=x.r=B.r=$.r;J.g=x.g=B.g=$.g;J.b=x.b=B.b=$.b;ya(M,o.v1.positionWorld,o.vertexNormalsWorld[0],J);ya(M,o.v2.positionWorld,o.vertexNormalsWorld[1],x);ya(M,o.v3.positionWorld,o.vertexNormalsWorld[2],B);t.r=(x.r+B.r)*0.5;t.g=(x.g+B.g)*0.5;t.b=(x.b+B.b)*0.5;N=Ia(J,x,B,t);ua(K,I,P,D,z,L,N,0,0,1,0,0,1)}else{R.r=$.r;R.g=$.g;R.b=$.b;ya(M,o.centroidWorld,o.normalWorld,R);A.r=s.color.r*
R.r;A.g=s.color.g*R.g;A.b=s.color.b*R.b;A.updateStyleString();s.wireframe?za(A.__styleString,s.wireframe_linewidth):Aa(A.__styleString)}else s.wireframe?za(s.color.__styleString,s.wireframe_linewidth):Aa(s.color.__styleString)}else if(s instanceof THREE.MeshDepthMaterial){Q=ia.near;w=ia.far;J.r=J.g=J.b=1-Da(l.positionScreen.z,Q,w);x.r=x.g=x.b=1-Da(F.positionScreen.z,Q,w);B.r=B.g=B.b=1-Da(y.positionScreen.z,Q,w);t.r=(x.r+B.r)*0.5;t.g=(x.g+B.g)*0.5;t.b=(x.b+B.b)*0.5;N=Ia(J,x,B,t);ua(K,I,P,D,z,L,N,0,
0,1,0,0,1)}else if(s instanceof THREE.MeshNormalMaterial){A.r=Ea(o.normalWorld.x);A.g=Ea(o.normalWorld.y);A.b=Ea(o.normalWorld.z);A.updateStyleString();s.wireframe?za(A.__styleString,s.wireframe_linewidth):Aa(A.__styleString)}}}function za(l,F){if(u!=l)h.strokeStyle=u=l;if(r!=F)h.lineWidth=r=F;h.stroke();G.inflate(F*2)}function Aa(l){if(v!=l)h.fillStyle=v=l;h.fill()}function ua(l,F,y,o,s,M,V,X,Y,da,ba,ea,va){var oa,fa;oa=V.width-1;fa=V.height-1;X*=oa;Y*=fa;da*=oa;ba*=fa;ea*=oa;va*=fa;y-=l;o-=F;s-=
l;M-=F;da-=X;ba-=Y;ea-=X;va-=Y;fa=1/(da*va-ea*ba);oa=(va*y-ba*s)*fa;ba=(va*o-ba*M)*fa;y=(da*s-ea*y)*fa;o=(da*M-ea*o)*fa;l=l-oa*X-y*Y;F=F-ba*X-o*Y;h.save();h.transform(oa,ba,y,o,l,F);h.clip();h.drawImage(V,0,0);h.restore()}function Ia(l,F,y,o){var s=~~(l.r*255),M=~~(l.g*255);l=~~(l.b*255);var V=~~(F.r*255),X=~~(F.g*255);F=~~(F.b*255);var Y=~~(y.r*255),da=~~(y.g*255);y=~~(y.b*255);var ba=~~(o.r*255),ea=~~(o.g*255);o=~~(o.b*255);aa[0]=s<0?0:s>255?255:s;aa[1]=M<0?0:M>255?255:M;aa[2]=l<0?0:l>255?255:l;
aa[4]=V<0?0:V>255?255:V;aa[5]=X<0?0:X>255?255:X;aa[6]=F<0?0:F>255?255:F;aa[8]=Y<0?0:Y>255?255:Y;aa[9]=da<0?0:da>255?255:da;aa[10]=y<0?0:y>255?255:y;aa[12]=ba<0?0:ba>255?255:ba;aa[13]=ea<0?0:ea>255?255:ea;aa[14]=o<0?0:o>255?255:o;sa.putImageData(Ca,0,0);xa.drawImage(ra,0,0);return ta}function Da(l,F,y){l=(l-F)/(y-F);return l*l*(3-2*l)}function Ea(l){l=(l+1)*0.5;return l<0?0:l>1?1:l}function Fa(l,F){var y=F.x-l.x,o=F.y-l.y,s=1/Math.sqrt(y*y+o*o);y*=s;o*=s;F.x+=y;F.y+=o;l.x-=y;l.y-=o}var Ba,Ja,T,ca,
qa,Ga,Ka,wa;this.autoClear?this.clear():h.setTransform(1,0,0,-1,j,g);c=d.projectScene(W,ia,this.sortElements);(U=W.lights.length>0)&&Ma(W);Ba=0;for(Ja=c.length;Ba<Ja;Ba++){T=c[Ba];G.empty();if(T instanceof THREE.RenderableParticle){k=T;k.x*=j;k.y*=g;ca=0;for(qa=T.materials.length;ca<qa;ca++)Na(k,T,T.materials[ca],W)}else if(T instanceof THREE.RenderableLine){k=T.v1;E=T.v2;k.positionScreen.x*=j;k.positionScreen.y*=g;E.positionScreen.x*=j;E.positionScreen.y*=g;G.addPoint(k.positionScreen.x,k.positionScreen.y);
G.addPoint(E.positionScreen.x,E.positionScreen.y);if(Z.instersects(G)){ca=0;for(qa=T.materials.length;ca<qa;)Oa(k,E,T,T.materials[ca++],W)}}else if(T instanceof THREE.RenderableFace3){k=T.v1;E=T.v2;C=T.v3;k.positionScreen.x*=j;k.positionScreen.y*=g;E.positionScreen.x*=j;E.positionScreen.y*=g;C.positionScreen.x*=j;C.positionScreen.y*=g;if(T.overdraw){Fa(k.positionScreen,E.positionScreen);Fa(E.positionScreen,C.positionScreen);Fa(C.positionScreen,k.positionScreen)}G.add3Points(k.positionScreen.x,k.positionScreen.y,
E.positionScreen.x,E.positionScreen.y,C.positionScreen.x,C.positionScreen.y);if(Z.instersects(G)){ca=0;for(qa=T.meshMaterials.length;ca<qa;){wa=T.meshMaterials[ca++];if(wa instanceof THREE.MeshFaceMaterial){Ga=0;for(Ka=T.faceMaterials.length;Ga<Ka;)(wa=T.faceMaterials[Ga++])&&Ha(k,E,C,T,wa,W)}else Ha(k,E,C,T,wa,W)}}}O.addRectangle(G)}h.setTransform(1,0,0,1,0,0)}};THREE.RenderableObject=function(){this.z=this.object=null};
THREE.RenderableFace3=function(){this.z=null;this.v1=new THREE.Vertex;this.v2=new THREE.Vertex;this.v3=new THREE.Vertex;this.centroidWorld=new THREE.Vector3;this.centroidScreen=new THREE.Vector3;this.normalWorld=new THREE.Vector3;this.vertexNormalsWorld=[];this.faceMaterials=this.meshMaterials=null;this.overdraw=false;this.uvs=[null,null,null]};THREE.RenderableParticle=function(){this.rotation=this.z=this.y=this.x=null;this.scale=new THREE.Vector2;this.materials=null};
THREE.RenderableLine=function(){this.z=null;this.v1=new THREE.Vertex;this.v2=new THREE.Vertex;this.materials=null};
